### ISSUE TITLE
"docker-compose up --build" hanging

### ISSUE THREAD

**Issue by nomadavid9** [souvikg10/rasa_multi_bot#1]
I run the docker-compose command, Docker begins to build the docker image, but at a certain point it has some sort of an issue with tensorflow and it'll hang the script indefinitely.

Here are the last few lines that are shown.

rasa_en_1  | 2018-12-03 21:48:43.593058: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use:
AVX2 FMA

rasa_fr_1  | 2018-12-03 21:48:44 WARNING  __main__  - Failed to load any agent model. Running Rasa Core server with out loaded model now. No module named multiarray

rasa_en_1  | 2018-12-03 21:48:44 WARNING  __main__  - Failed to load any agent model. Running Rasa Core server with out loaded model now. No module named multiarray

**Comment by souvikg10** [comment]
Hi sorry
It was my mistake. The premise is based on the article  here: https://blog.usejournal.com/building-a-multi-lingual-chatbot-using-rasa-and-chatfuel-cca20cbc645a

Before you start the build, you should have a trained model already. if you are using my docker-compose file, you will already find the models in the data folder. It seems you have modified the docker-compose to point towards another model path

**Comment by nomadavid9** [comment]
Ahh I see, sorry I didn't follow the tutorial the first time. Have since followed it and am able to stand the bot up no problem! thanks!
